server:
  port: 8081

spring:
  profiles:
    active: local

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 500MB

  #thymeleaf 설정
#  이거 꼭 gradle에 의존성 추가 해줘야함.
#  implementation 'org.springframework.boot:spring-boot-starter-thymeleaf'
#  implementation group: 'nz.net.ultraq.thymeleaf', name: 'thymeleaf-layout-dialect', version: '2.5.2'
  thymeleaf:
    cache: false
    enabled: true
    encoding: UTF-8
    suffix: .html
    prefix: classpath:/templates/

#  mail:
#    host: smtp.gmail.com
#    port: 587
#    username: epayday.mail.send@gmail.com
#    password: zjsprsmtp!!
#    properties:
#      mail:
#        smtp:
#          auth: true
#          starttls:
#            enable: true

#mybatis:
#  mapper-locations: mapper/**/*.xml
#  config-location: classpath:/mybatis-config.xml
